### PR TITLE
Added optional argument to methods fit_from_cfg to allow to pass an output yaml file

### PR DESCRIPTION
**Pull request by hanase**
Affects (segmented) regression models and (segmented) discrete choice models. The default behavior of those models did not change.

### CODE REVIEW

**Comment by hanase** [comment]
Not sure why the checks fail - it does not seem to be related to the changes.

**Comment by janowicz** [comment]
Thanks @hanase!   We'll look into the failing checks.

**Comment by fscottfoti** [comment]
Yeah that's awesome - thanks @hanase

**Comment by pksohn** [comment]
We just reran the Travis CI build and tests passed fine! I think it was a temporary Conda issue.

**Comment by janowicz** [comment]
The additional optional arguments look good to me  :thumbsup:

**Pull request merged**
