### PR TITLE
fix 2 typos

### PR DESCRIPTION
**Pull request by tombuckley**

### CODE REVIEW

**Comment by jiffyclub** [comment]
I'm going to have to leave this un-merged for a little bit while we sort some copyright/legal stuff related to the project, but thanks for the fixes, we'll get them in as soon as we can.

**Comment by buckleytom** [comment]
roger

**Comment by Eh2406** [comment]
What is the status on this?

**Comment by janowicz** [comment]
Thanks @tombuckley! This pull request relates to the simulation framework bits of the documentation, which have been moved over to the `orca` repository.  I'll re-open these typo edits as a pull request over there.

**Pull request closed without merging**
