### PR TITLE
updated deprecated `diff` function from pandas.Index

### PR DESCRIPTION
**Pull request by moritz-kirmse-forcity**
changed `Index.diff()` to `Index.difference`

### CODE REVIEW

**Comment by janowicz** [comment]
Looks good, thanks!

**Comment by janowicz** [comment]
Does this change necessitate a different minimum pandas version in setup.py?
https://github.com/UDST/urbansim/blob/master/setup.py#L38

**Comment by Eh2406** [comment]
yes, I think. http://pandas.pydata.org/pandas-docs/version/0.13.1/api.html#index
looks like it was add in .15 http://pandas.pydata.org/pandas-docs/version/0.15.0/generated/pandas.Index.difference.html

**Comment by moritz-kirmse-forcity** [comment]
ah, thanks, I'll update the PR

**Comment by janowicz** [comment]
Thanks @moritz-kirmse-forcity!

**Pull request merged**
