### PR TITLE
performance improvement to developer pick

### PR DESCRIPTION
**Pull request by Eh2406**
random.choice only needs to pull target_units of projects. and only needs to run if we are not using all or none of the projects.

### CODE REVIEW

**Comment by fscottfoti** [comment]
I have a question about this one - the biggest change is here `min(len(df.index), target_units)`.  The problem as I see it is that target_units is actually the sum of an attribute of all the developments you're picking from (the number of units in each development).  So it's not like it's the target number of developments - we don't know how many developments we're going to need until we pick them based on their profitability and sum up the number of units in them.  So you could definitely write a "for" loop to pick developments one by one and sum up the units but I actually think that would be slower in most cases than essentially sorting the vector of developments which is what this is doing.  In other words, I think the code makes sense but only because I'm trying to avoid for loops at all cost.  At any rate I just think this code isn't quite right since many developments might have 100s or 1000s of units I think this is a min of apples and oranges.  Does that make sense - maybe I'm missing something too?

**Comment by Eh2406** [comment]
I should have explained. Yes it is a min of apples and oranges. However we know that all developments have `net_units > 0` which implies that we have `target_units >= len(new developments)` So I think it is safe to only choice target_units meny. I should probably add a comment.

If I have missed something then perhaps `np.random.permutation` or `np.random.shuffle` is clearer and faster than `np.random.choice(x, size=len(x), replace=False)`

**Comment by fscottfoti** [comment]
Right, agreed that it won't actually hurt anything.  I'm just guessing that len(df.index) will be less than target_units usually but that's certainly not always the case.  A comment would help just to make it clear that's what's intended thanks!

Yes it is a shuffle but the `p` parameter is the catch - we definitely want to bias the developments we choose by the probabilities that are passed in, hence the random.choice with n=len(df).  Sometimes it feels like we jump through a lot of hoops to avoid for loops doesn't it?

**Comment by Eh2406** [comment]
Do you have any other way to get closer to picking the right number to start with?

Yes, fast loops is one of the things I love about developing in Rust.

Ahh, the 'p' is important. I just spent all morning doing a deep dive into whether

    np.random.choice(x, size=len(x), replace=False)[:n]

and 

    np.random.choice(x, size=n, replace=False)

are equivalent. They are. Because np.unique returns the first occurrence. A deep dive for not much gain, lol.

**Comment by fscottfoti** [comment]
This change looks fine to me - are you ready to merge?  Thanks for adding the comment...

And yeah Rust and a few other languages might give Python a run for its money someday.  My personal preference is Julia, especially if it eventually gets a big stats following ;)

**Comment by Eh2406** [comment]
+1I'm ready to merg.

**Pull request merged**
