### PR TITLE
round `np.ndarray` instead of `pd.Series`

### PR DESCRIPTION
**Pull request by juanshishido**
All tests passing

### CODE REVIEW

**Comment by fscottfoti** [comment]
Ahh I see.  Do you have idea why the tests failed but the code generally ran?  I mean, why would the test fail?  Are there some added checks in numpy when pytest runs or something?  Any ideas?

**Comment by juanshishido** [comment]
@fscottfoti Not being too familiar with the codebase, I'm not really sure. But I have some thoughts.

You said the code generally ran? You mean you tested it locally? What version of pandas are you on? These issues seem to stem from pandas==0.18.0. For more information on this rounding bug, see [here](https://github.com/pydata/pandas/issues/12600). I imagine it would fail if you call `Developer.pick()` (prior to the change I submitted).

I asked about this in `pydata/pandas` on Gitter, which is where I got the link above. Someone suggested using `pd.Series(range(10).round()` instead of `np.round(pd.Series(range(10)).values)`, like in my change to `developer.py`.

**Comment by fscottfoti** [comment]
I'm cool with using pd.Series.round on this one - what do you think?

**Comment by juanshishido** [comment]
I'm fine with that, too. Probably preferred.

The change would look like:

```
df['residential_units'] = (df.residential_sqft / df.ave_unit_size).round()
df['job_spaces'] = (df.non_residential_sqft / bldg_sqft_per_job).round()
```

**Comment by waddell** [comment]
Works for me.

**Comment by fscottfoti** [comment]
Likewise.

**Pull request merged**
